### ISSUE TITLE
YAML-CPP no longer builds with Boost 1.67

### ISSUE THREAD

**Issue by jmcornell** [GambitBSM/gambit#26]
With the newest version of Boost (1.67), yaml-cpp no longer builds. The error is:

In file included from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/iterator.h:13:0,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/impl.h:11,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/convert.h:17,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/src/convert.cpp:3:
/Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/detail/iterator.h: In member function 'void YAML::detail::iterator_base<V>::increment()':
/Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/detail/iterator.h:48:47: error: 'next' is not a member of 'boost'
   void increment() { this->base_reference() = boost::next(this->base()); }
                                               ^~~~~
/Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/detail/iterator.h:48:47: note: suggested alternatives:
In file included from /usr/local/Cellar/gcc@6/6.4.0_2/include/c++/6.4.0/bits/stl_algobase.h:66:0,
                 from /usr/local/Cellar/gcc@6/6.4.0_2/include/c++/6.4.0/algorithm:61,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/src/convert.cpp:1:
/usr/local/Cellar/gcc@6/6.4.0_2/include/c++/6.4.0/bits/stl_iterator_base_funcs.h:205:5: note:   'std::next'
     next(_ForwardIterator __x, typename
     ^~~~
In file included from /usr/local/include/boost/mpl/next.hpp:17:0,
                 from /usr/local/include/boost/mpl/bind.hpp:25,
                 from /usr/local/include/boost/mpl/lambda.hpp:18,
                 from /usr/local/include/boost/mpl/apply.hpp:25,
                 from /usr/local/include/boost/iterator/iterator_facade.hpp:36,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/detail/node_iterator.h:12,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/detail/iterator.h:12,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/iterator.h:13,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/impl.h:11,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/include/yaml-cpp/node/convert.h:17,
                 from /Users/jonathan/GAMBIT/master/contrib/yaml-cpp-0.5.3/src/convert.cpp:3:
/usr/local/include/boost/mpl/next_prior.hpp:29:8: note:   'boost::mpl::next'
 struct next
        ^~~~

Looking at https://www.boost.org/users/history/version_1_67_0.html, you can see that the problem is likely:

Breaking change: <boost/utility.hpp> header no longer includes boost::next and boost::prior as they have been moved to the iterator module. Instead include <boost/next_prior.hpp>. Other uses of <boost/utility.hpp> are discouraged, it's better to use the header for the specific functionality instead.

yaml-cpp-0.6.2 removes the dependency on Boost (see here: https://github.com/jbeder/yaml-cpp/releases), so it seems like upgrading yaml-cpp is the best solution. Do others agree? If I have some time, I might try to do this, but if someone else wants to take a shot, please go ahead.
